version: 2
jobs:
  build:
    docker:
      # https://hub.docker.com/r/circleci/android/tags
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Touch local.properties
          command: touch local.properties
      - run:
          name: Add google-services.json
          command: echo $GOOGLE_SERVICES_JSON | base64 --decode --ignore-garbage > ${HOME}/project/app/google-services.json
      - run:
          name: Add debug/google-services.json
          command: echo $GOOGLE_SERVICES_JSON_DEBUG | base64 --decode --ignore-garbage > ${HOME}/project/app/src/debug/google-services.json
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
